import {fileURLToPath} from 'node:url';

export default defineNuxtConfig({
    modules: [
        '@nuxt/eslint',
        '@nuxt/ui',
        '@nuxt/icon',
    ],

    css: ['~/assets/css/main.css'],

    ssr: false,

    devtools: {enabled: false},

    devServer: {port: 3235},

    colorMode: {preference: 'light'},

    icon: {
        serverBundle: {collections: ['lucide']},
        clientBundle: {icons: [
            'lucide:arrow-down',
            'lucide:arrow-left',
            'lucide:arrow-right',
            'lucide:arrow-up',
            'lucide:book-open',
            'lucide:check',
            'lucide:chevron-down',
            'lucide:chevron-left',
            'lucide:chevron-right',
            'lucide:chevron-up',
            'lucide:chevrons-left',
            'lucide:chevrons-right',
            'lucide:circle-alert',
            'lucide:circle-check',
            'lucide:circle-stop',
            'lucide:circle-x',
            'lucide:copy',
            'lucide:ellipsis',
            'lucide:external-link',
            'lucide:eye',
            'lucide:eye-off',
            'lucide:file',
            'lucide:file-text',
            'lucide:folder',
            'lucide:folder-open',
            'lucide:hand',
            'lucide:hash',
            'lucide:info',
            'lucide:layout-grid',
            'lucide:lightbulb',
            'lucide:list',
            'lucide:loader-2',
            'lucide:loader-circle',
            'lucide:menu',
            'lucide:minus',
            'lucide:monitor',
            'lucide:moon',
            'lucide:move-horizontal',
            'lucide:move-vertical',
            'lucide:panel-left',
            'lucide:panel-right-close',
            'lucide:panel-right-open',
            'lucide:plus',
            'lucide:refresh-cw',
            'lucide:save',
            'lucide:search',
            'lucide:search-x',
            'lucide:sun',
            'lucide:text-cursor',
            'lucide:type',
            'lucide:triangle-alert',
            'lucide:upload',
            'lucide:x',
            'lucide:zoom-in',
            'lucide:scan-text',
            'lucide:play',
            'lucide:alert-circle',
            'lucide:check-circle',
            'lucide:scaling',
            'lucide:clock',
        ]},
    },

    vite: {
        resolve: {alias: {app: fileURLToPath(new URL('./app', import.meta.url))}},
        build: {rollupOptions: {output: {manualChunks: {'vendor-pdfjs': ['pdfjs-dist']}}}},
        optimizeDeps: {
            include: [
                '@vueuse/core',
                'devalue',
                'unhead',
                '@unhead/vue',
                'vue-router',
                'ofetch',
                'hookable',
                'unctx',
                'klona',
                'destr',
                'scule',
                '@vue/devtools-api',
                '@iconify/vue',
            ],
            exclude: ['pdfjs-dist'],
        },
        server: {watch: {usePolling: false}},
    },

    compatibilityDate: '2025-01-01',
});
