import {fileURLToPath} from 'node:url';

export default defineNuxtConfig({
    modules: [
        '@nuxt/eslint',
        '@nuxt/ui',
        '@nuxt/icon',
        '@nuxtjs/i18n',
    ],

    css: [
        '~/assets/css/main.css',
        '~/assets/css/pdfjs-overrides.css',
        '~/assets/css/pdf-comment-markers.css',
        '~/assets/css/pdf-comment-ui.css',
        '~/assets/css/pdf-search-highlights.css',
        '~/assets/css/pdf-animations.css',
        '~/assets/css/pdf-debug-overlays.css',
    ],

    ssr: false,

    // Disable SPA loading template - causes jerky size changes due to scrollbar appearance
    spaLoadingTemplate: false,

    devtools: {enabled: false},

    devServer: {port: 3235},

    colorMode: {preference: 'light'},

    i18n: {
        restructureDir: 'app',
        locales: [
            { code: 'en', file: 'en.json', name: 'English' },
            { code: 'ru', file: 'ru.json', name: 'Русский' },
            { code: 'fr', file: 'fr.json', name: 'Français' },
            { code: 'de', file: 'de.json', name: 'Deutsch' },
            { code: 'es', file: 'es.json', name: 'Español' },
            { code: 'it', file: 'it.json', name: 'Italiano' },
            { code: 'pt', file: 'pt.json', name: 'Português' },
            { code: 'nl', file: 'nl.json', name: 'Nederlands' },
        ],
        defaultLocale: 'en',
        lazy: false,
        langDir: 'locales/',
        strategy: 'no_prefix',
    },

    icon: {
        serverBundle: {collections: ['lucide']},
        clientBundle: {icons: [
            'lucide:arrow-down',
            'lucide:arrow-left',
            'lucide:arrow-right',
            'lucide:arrow-up',
            'lucide:book-open',
            'lucide:bookmark',
            'lucide:check',
            'lucide:chevron-down',
            'lucide:chevron-left',
            'lucide:chevron-right',
            'lucide:chevron-up',
            'lucide:chevrons-down',
            'lucide:chevrons-left',
            'lucide:chevrons-right',
            'lucide:chevrons-up',
            'lucide:circle-alert',
            'lucide:circle-check',
            'lucide:circle-stop',
            'lucide:circle-x',
            'lucide:copy',
            'lucide:ellipsis',
            'lucide:external-link',
            'lucide:eye',
            'lucide:eye-off',
            'lucide:file',
            'lucide:file-text',
            'lucide:folder',
            'lucide:folder-open',
            'lucide:hand',
            'lucide:hash',
            'lucide:highlighter',
            'lucide:info',
            'lucide:layout-grid',
            'lucide:lightbulb',
            'lucide:list',
            'lucide:loader-2',
            'lucide:loader-circle',
            'lucide:menu',
            'lucide:message-circle',
            'lucide:message-square',
            'lucide:minus',
            'lucide:monitor',
            'lucide:moon',
            'lucide:move-horizontal',
            'lucide:move-vertical',
            'lucide:mouse-pointer',
            'lucide:panel-left',
            'lucide:panel-right-close',
            'lucide:panel-right-open',
            'lucide:pen-tool',
            'lucide:plus',
            'lucide:pencil',
            'lucide:square-pen',
            'lucide:grip-vertical',
            'lucide:refresh-cw',
            'lucide:save',
            'lucide:save-all',
            'lucide:search',
            'lucide:search-x',
            'lucide:scroll',
            'lucide:sun',
            'lucide:text-cursor',
            'lucide:trash-2',
            'lucide:type',
            'lucide:triangle-alert',
            'lucide:undo-2',
            'lucide:upload',
            'lucide:user',
            'lucide:x',
            'lucide:zoom-in',
            'lucide:scan-text',
            'lucide:play',
            'lucide:alert-circle',
            'lucide:check-circle',
            'lucide:scaling',
            'lucide:clock',
            'lucide:wand-2',
            'lucide:redo-2',
            'lucide:underline',
            'lucide:strikethrough',
            'lucide:waves',
            'lucide:square',
            'lucide:circle',
            'lucide:minus',
            'lucide:arrow-up-right',
            'lucide:stamp',
            'lucide:settings',
            'lucide:sticky-note',
            'lucide:languages',
            'circle-flags:gb',
            'circle-flags:ru',
            'circle-flags:fr',
            'circle-flags:de',
            'circle-flags:es',
            'circle-flags:it',
            'circle-flags:pt',
            'circle-flags:nl',
            'lucide:file-output',
            'lucide:file-plus',
            'lucide:rotate-cw',
            'lucide:rotate-ccw',
        ]},
    },

    vite: {
        resolve: {alias: {'@app': fileURLToPath(new URL('./app', import.meta.url))}},
        build: {rollupOptions: {output: {manualChunks: {'vendor-pdfjs': ['pdfjs-dist']}}}},
        optimizeDeps: {
            include: [
                '@vueuse/core',
                'devalue',
                'unhead',
                '@unhead/vue',
                'vue-router',
                'ofetch',
                'hookable',
                'unctx',
                'klona',
                'destr',
                'scule',
                '@vue/devtools-api',
                '@iconify/vue',
            ],
            exclude: ['pdfjs-dist'],
        },
        server: {watch: {usePolling: false}},
    },

    compatibilityDate: '2025-01-01',
});
