import type {IWorkspaceExpose} from '@app/types/workspaceExpose';

const unimplementedWorkspaceExposeMethod = (): never => {
    throw new Error('Unexpected workspace expose fixture call');
};

const defaultWorkspaceExpose = {
    captureSplitPayload: unimplementedWorkspaceExposeMethod,
    closeAllDropdowns: unimplementedWorkspaceExposeMethod,
    commentAtPoint: unimplementedWorkspaceExposeMethod,
    createRecoverySnapshotBytes: unimplementedWorkspaceExposeMethod,
    getAllShapes: unimplementedWorkspaceExposeMethod,
    getAutomationStateSnapshot: unimplementedWorkspaceExposeMethod,
    getDeletedEmbeddedShapeAnnotationIds: unimplementedWorkspaceExposeMethod,
    getDeletedEmbeddedShapeStableKeys: unimplementedWorkspaceExposeMethod,
    getToolbarSnapshot: unimplementedWorkspaceExposeMethod,
    handleCloseFileFromUi: unimplementedWorkspaceExposeMethod,
    handleCombineImages: unimplementedWorkspaceExposeMethod,
    handleConvertToPdf: unimplementedWorkspaceExposeMethod,
    handleCrop: unimplementedWorkspaceExposeMethod,
    handleCropPages: unimplementedWorkspaceExposeMethod,
    handleDeletePages: unimplementedWorkspaceExposeMethod,
    handleDisableDragMode: unimplementedWorkspaceExposeMethod,
    handleEnableDragMode: unimplementedWorkspaceExposeMethod,
    handleExportDocx: unimplementedWorkspaceExposeMethod,
    handleExportImages: unimplementedWorkspaceExposeMethod,
    handleExportMultiPageTiff: unimplementedWorkspaceExposeMethod,
    handleExtractPages: unimplementedWorkspaceExposeMethod,
    handleFitHeight: unimplementedWorkspaceExposeMethod,
    handleFitWidth: unimplementedWorkspaceExposeMethod,
    handleGoToPage: unimplementedWorkspaceExposeMethod,
    handleInsertImageFromFile: unimplementedWorkspaceExposeMethod,
    handleInsertPages: unimplementedWorkspaceExposeMethod,
    handleOpenFileDirectBatchWithPersist: unimplementedWorkspaceExposeMethod,
    handleOpenFileDirectWithPersist: unimplementedWorkspaceExposeMethod,
    handleOpenFileFromUi: unimplementedWorkspaceExposeMethod,
    handleOpenFileWithResult: unimplementedWorkspaceExposeMethod,
    handleActualSize: unimplementedWorkspaceExposeMethod,
    handleCaptureRegion: unimplementedWorkspaceExposeMethod,
    handlePageDelete: unimplementedWorkspaceExposeMethod,
    handlePageMove: unimplementedWorkspaceExposeMethod,
    handlePageReorder: unimplementedWorkspaceExposeMethod,
    handlePageRotate: unimplementedWorkspaceExposeMethod,
    handlePasteImageFromClipboard: unimplementedWorkspaceExposeMethod,
    handlePrint: unimplementedWorkspaceExposeMethod,
    handlePrintCurrentPage: unimplementedWorkspaceExposeMethod,
    handleQuickNote: unimplementedWorkspaceExposeMethod,
    handleRedo: unimplementedWorkspaceExposeMethod,
    handleSelectAll: unimplementedWorkspaceExposeMethod,
    handleRepairSave: unimplementedWorkspaceExposeMethod,
    handleOptimizePdfForInteraction: unimplementedWorkspaceExposeMethod,
    handleSave: unimplementedWorkspaceExposeMethod,
    handleSaveAs: unimplementedWorkspaceExposeMethod,
    handleToggleContinuousScroll: unimplementedWorkspaceExposeMethod,
    handleToggleSidebar: unimplementedWorkspaceExposeMethod,
    handleUndo: unimplementedWorkspaceExposeMethod,
    handleViewModeFacing: unimplementedWorkspaceExposeMethod,
    handleViewModeFacingFirstSingle: unimplementedWorkspaceExposeMethod,
    handleViewModeSingle: unimplementedWorkspaceExposeMethod,
    handleViewRotationCcw: unimplementedWorkspaceExposeMethod,
    handleViewRotationCw: unimplementedWorkspaceExposeMethod,
    handleRotateCcw: unimplementedWorkspaceExposeMethod,
    handleRotateCw: unimplementedWorkspaceExposeMethod,
    handleOcrComplete: unimplementedWorkspaceExposeMethod,
    highlightSelection: unimplementedWorkspaceExposeMethod,
    pageOpsDelete: unimplementedWorkspaceExposeMethod,
    pageOpsInsert: unimplementedWorkspaceExposeMethod,
    pageOpsMove: unimplementedWorkspaceExposeMethod,
    pageOpsReorder: unimplementedWorkspaceExposeMethod,
    readAgentResource: unimplementedWorkspaceExposeMethod,
    restoreSplitPayload: unimplementedWorkspaceExposeMethod,
    runAgentAction: unimplementedWorkspaceExposeMethod,
    scrollToPage: unimplementedWorkspaceExposeMethod,
    setCustomZoomFromDisplay: unimplementedWorkspaceExposeMethod,
    setViewRotation: unimplementedWorkspaceExposeMethod,
    handleZoomIn: unimplementedWorkspaceExposeMethod,
    handleZoomOut: unimplementedWorkspaceExposeMethod,
    waitForDocumentOpenSettled: unimplementedWorkspaceExposeMethod,
    hasPdf: false,
};

export function createWorkspaceExposeFixture(
    overrides: Partial<IWorkspaceExpose> = {},
): IWorkspaceExpose {
    return {
        ...defaultWorkspaceExpose,
        ...overrides,
    } satisfies IWorkspaceExpose;
}
