import type {IDocumentsService} from '@electron/features/documents/documentsService';

const unimplementedDocumentsServiceMethod = (): never => {
    throw new Error('Unexpected documents service fixture call');
};

const defaultDocumentsService = {
    analyzePdfConformance: unimplementedDocumentsServiceMethod,
    applyPdfNativeMutationsToWorkingCopy: unimplementedDocumentsServiceMethod,
    beginPdfAnnotationIndex: unimplementedDocumentsServiceMethod,
    beginPdfEmbeddedShapeIndex: unimplementedDocumentsServiceMethod,
    beginSavePdfData: unimplementedDocumentsServiceMethod,
    cancelOpenDocumentDirectBatch: unimplementedDocumentsServiceMethod,
    cancelPdfPrint: unimplementedDocumentsServiceMethod,
    cancelStagedSerializedPdf: unimplementedDocumentsServiceMethod,
    cleanupFile: unimplementedDocumentsServiceMethod,
    clearRecentFiles: unimplementedDocumentsServiceMethod,
    cloneStagedPdfNativeMutationToWorkingCopy: unimplementedDocumentsServiceMethod,
    commitStagedPdfNativeMutations: unimplementedDocumentsServiceMethod,
    commitStagedSerializedPdf: unimplementedDocumentsServiceMethod,
    createManagedTempFileHandle: unimplementedDocumentsServiceMethod,
    createWorkingCopyFromData: unimplementedDocumentsServiceMethod,
    createWorkingCopyFromPath: unimplementedDocumentsServiceMethod,
    fileExists: unimplementedDocumentsServiceMethod,
    getDocumentRevision: unimplementedDocumentsServiceMethod,
    getPdfNativePageSizes: unimplementedDocumentsServiceMethod,
    getPdfOpeningGeometry: unimplementedDocumentsServiceMethod,
    getRecentFiles: unimplementedDocumentsServiceMethod,
    getWorkingCopyBackingStatus: unimplementedDocumentsServiceMethod,
    onWorkingCopyBackingStatusChanged: unimplementedDocumentsServiceMethod,
    openCombineDialog: unimplementedDocumentsServiceMethod,
    openDocumentDialog: unimplementedDocumentsServiceMethod,
    openDocumentDirect: unimplementedDocumentsServiceMethod,
    openDocumentDirectBatch: unimplementedDocumentsServiceMethod,
    openFolderDialog: unimplementedDocumentsServiceMethod,
    openImageDialog: unimplementedDocumentsServiceMethod,
    optimizePdfAsCopy: unimplementedDocumentsServiceMethod,
    optimizePdfForInteraction: unimplementedDocumentsServiceMethod,
    parsePdfAnnotations: unimplementedDocumentsServiceMethod,
    printPdfData: unimplementedDocumentsServiceMethod,
    printPdfPath: unimplementedDocumentsServiceMethod,
    readFile: unimplementedDocumentsServiceMethod,
    readFileRange: unimplementedDocumentsServiceMethod,
    readPdfPageLabelRanges: unimplementedDocumentsServiceMethod,
    readPdfAnnotationIndexChunk: unimplementedDocumentsServiceMethod,
    readPdfEmbeddedShapeIndexChunk: unimplementedDocumentsServiceMethod,
    readTextFile: unimplementedDocumentsServiceMethod,
    releaseManagedTempFileHandle: unimplementedDocumentsServiceMethod,
    releasePdfAnnotationIndex: unimplementedDocumentsServiceMethod,
    releasePdfEmbeddedShapeIndex: unimplementedDocumentsServiceMethod,
    removeRecentFile: unimplementedDocumentsServiceMethod,
    repairPdf: unimplementedDocumentsServiceMethod,
    replaceWorkingCopyFromPath: unimplementedDocumentsServiceMethod,
    replaceWorkingCopyFromStagedPdfNativeMutation: unimplementedDocumentsServiceMethod,
    saveDocxAs: unimplementedDocumentsServiceMethod,
    saveFileStructured: unimplementedDocumentsServiceMethod,
    savePdfAs: unimplementedDocumentsServiceMethod,
    savePdfData: unimplementedDocumentsServiceMethod,
    savePdfDialog: unimplementedDocumentsServiceMethod,
    savePdfNoteChanges: unimplementedDocumentsServiceMethod,
    savePdfNoteTextUpdates: unimplementedDocumentsServiceMethod,
    setMenuDocumentState: unimplementedDocumentsServiceMethod,
    setMenuTabCount: unimplementedDocumentsServiceMethod,
    setWindowTitle: unimplementedDocumentsServiceMethod,
    showItemInFolder: unimplementedDocumentsServiceMethod,
    statFile: unimplementedDocumentsServiceMethod,
    validatePdfPath: unimplementedDocumentsServiceMethod,
    writeDocxFile: unimplementedDocumentsServiceMethod,
    writeFile: unimplementedDocumentsServiceMethod,
};

export function createDocumentsServiceFixture(
    overrides: Partial<IDocumentsService> = {},
): IDocumentsService {
    return {
        ...defaultDocumentsService,
        ...overrides,
    } satisfies IDocumentsService;
}
