export const SCAN_CLEANUP_TOOLBAR_PRIMARY_ACTION_CLASS = 'scan-cleanup-toolbar-primary-action';
export const SCAN_CLEANUP_TOOLBAR_PRIMARY_ACTION_SELECTOR = `.${SCAN_CLEANUP_TOOLBAR_PRIMARY_ACTION_CLASS}`;

export const SCAN_CLEANUP_TOOLBAR_COUNT_CLASS = 'scan-cleanup-toolbar-count';
export const SCAN_CLEANUP_TOOLBAR_COUNT_SELECTOR = `.${SCAN_CLEANUP_TOOLBAR_COUNT_CLASS}`;

export const SCAN_CLEANUP_RUN_METER_CLASS = 'scan-cleanup-run-meter';
export const SCAN_CLEANUP_RUN_METER_SELECTOR = `.${SCAN_CLEANUP_RUN_METER_CLASS}`;

export const SCAN_CLEANUP_TOOLBAR_CANCEL_DETECTION_CLASS = 'scan-cleanup-toolbar-cancel-detection';
export const SCAN_CLEANUP_TOOLBAR_CANCEL_DETECTION_SELECTOR = `.${SCAN_CLEANUP_TOOLBAR_CANCEL_DETECTION_CLASS}`;
