import { readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeGeneratedFileIfChanged } from '@scripts/writeGeneratedFileIfChanged';
import {
    AVAILABLE_OCR_LANGUAGES,
    BUNDLED_OCR_LANGUAGE_CODES,
} from '@contracts/ocrLanguages';
import {
    ELECTRON_BUILDER_PLATFORM_KEYS,
    GLOBAL_PACKAGED_RESOURCES,
    NATIVE_TOOL_RESOURCE_FAMILIES,
    type INativeToolResourceFamily,
    type TNativeResourcePlatform,
} from '@scripts/nativeResourceManifest';
import {TESSERACT_PDF_FONT_FILE_NAME} from '@scripts/tesseractPdfFont';

export interface IElectronBuilderResourcePlan {
    content: string;
    relativePath: string;
}

export interface IGenerateElectronBuilderResourcesOptions { projectRoot?: string; }

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRelativePath = '.tmp/generated-electron-builder-resources.yml';
const tessdataRelativePath = 'resources/tesseract/tessdata';

function platformTag(platform: TNativeResourcePlatform) {
    return `${platform}-\${arch}`;
}

function renderNativeResource(
    family: INativeToolResourceFamily,
    platform: TNativeResourcePlatform,
) {
    const lines = [
        `    - from: ${path.posix.join(...family.sourceRootSegments, platformTag(platform))}`,
        `      to: ${path.posix.join(...family.stagedRootSegments, platformTag(platform))}`,
    ];
    const filters = family.packageFiltersByPlatform?.[platform];
    if (filters) {
        lines.push(
            '      filter:',
            ...filters.map(filter => `        - "${filter}"`),
        );
    }
    return lines.join('\n');
}

function supportsPlatform(family: INativeToolResourceFamily, platform: TNativeResourcePlatform) {
    return family.packagedEntries.some(entry => !entry.platforms || entry.platforms.includes(platform));
}

export function renderElectronBuilderResources(
    bundledOcrCodes: readonly string[] = BUNDLED_OCR_LANGUAGE_CODES,
    nativeResourceFamilies: readonly INativeToolResourceFamily[] = NATIVE_TOOL_RESOURCE_FAMILIES,
) {
    const rootResources = [
        'extraResources:',
        ...GLOBAL_PACKAGED_RESOURCES.flatMap(resource => {
            const filters = resource.id === 'tessdata'
                ? [
                    ...bundledOcrCodes.map(code => `${code}.traineddata`),
                    ...(resource.requiredFiles ?? []),
                ]
                : resource.filters;
            return [
                `  - from: ${path.posix.join(...resource.sourceSegments)}`,
                `    to: ${path.posix.join(...resource.stagedSegments)}`,
                ...(filters
                    ? [
                        '    filter:',
                        ...filters.map(filter => `      - ${filter}`),
                    ]
                    : []),
            ];
        }),
    ].join('\n');
    const platformResources = Object.entries(ELECTRON_BUILDER_PLATFORM_KEYS).map(([
        platform,
        configKey,
    ]) => [
        `${configKey}:`,
        '  extraResources:',
        ...nativeResourceFamilies
            .filter(family => supportsPlatform(family, platform as TNativeResourcePlatform))
            .map(family => renderNativeResource(
                family,
                platform as TNativeResourcePlatform,
            )),
    ].join('\n')).join('\n\n');

    return [
        '# Generated by scripts/generateElectronBuilderResources.ts. Do not edit.',
        '',
        rootResources,
        '',
        platformResources,
        '',
    ].join('\n');
}

async function assertOcrRegistryMatchesResources(root: string) {
    const registryCodes: string[] = AVAILABLE_OCR_LANGUAGES
        .map(language => language.code)
        .sort();
    const tessdataDirectory = path.join(root, tessdataRelativePath);
    const tessdataCodes = (await readdir(tessdataDirectory, {withFileTypes: true}))
        .filter(entry => entry.isFile() && entry.name.endsWith('.traineddata'))
        .map(entry => entry.name.slice(0, -'.traineddata'.length))
        .sort();
    const hasPdfFont = (await readdir(tessdataDirectory, {withFileTypes: true}))
        .some(entry => entry.isFile() && entry.name === TESSERACT_PDF_FONT_FILE_NAME);
    const bundledCodes = [...BUNDLED_OCR_LANGUAGE_CODES].sort();
    const missingModels = registryCodes.filter(code => !tessdataCodes.includes(code));
    const unregisteredModels = tessdataCodes.filter(code => !registryCodes.includes(code));
    const invalidBundledModels = bundledCodes.filter(code => !tessdataCodes.includes(code));

    if (!hasPdfFont || missingModels.length > 0 || unregisteredModels.length > 0 || invalidBundledModels.length > 0) {
        throw new Error([
            'OCR registry and tessdata_best resources are out of sync.',
            `Missing Tesseract PDF font: ${hasPdfFont ? '(none)' : TESSERACT_PDF_FONT_FILE_NAME}`,
            `Missing traineddata: ${missingModels.join(', ') || '(none)'}`,
            `Unregistered traineddata: ${unregisteredModels.join(', ') || '(none)'}`,
            `Invalid bundled defaults: ${invalidBundledModels.join(', ') || '(none)'}`,
        ].join('\n'));
    }
}

export async function createElectronBuilderResourcePlan(
    options: IGenerateElectronBuilderResourcesOptions = {},
): Promise<IElectronBuilderResourcePlan> {
    const root = options.projectRoot ?? projectRoot;
    await assertOcrRegistryMatchesResources(root);
    return {
        content: renderElectronBuilderResources(),
        relativePath: generatedRelativePath,
    };
}

export async function generateElectronBuilderResources(
    options: IGenerateElectronBuilderResourcesOptions = {},
) {
    const root = options.projectRoot ?? projectRoot;
    const plan = await createElectronBuilderResourcePlan({projectRoot: root});
    return writeGeneratedFileIfChanged(path.join(root, plan.relativePath), plan.content);
}

const isDirectCliRun = process.argv[1] !== undefined
    && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectCliRun && await generateElectronBuilderResources()) {
    console.info('Generated Electron Builder resource manifest.');
}
