import { getErrorMessage } from '@contracts/getErrorMessage';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
    type IGeneratedRustNativeToolProtocol,
} from '@contracts/nativeToolProtocols';
import { writeGeneratedFileIfChanged } from '@scripts/writeGeneratedFileIfChanged';

export interface IGenerateNativeToolProtocolsOptions {
    projectRoot?: string;
    protocols?: readonly IGeneratedRustNativeToolProtocol[];
}

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRustRelativePath = 'native/evb-native-support/src/generated_native_tool_protocols.rs';

function rustConstantName(protocol: IGeneratedRustNativeToolProtocol) {
    return protocol.stagingName.replaceAll('-', '_').toUpperCase();
}

export function renderRustNativeToolProtocols(
    protocols: readonly IGeneratedRustNativeToolProtocol[] = GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
) {
    const constants = protocols.map((protocol) => {
        const name = rustConstantName(protocol);
        const constructor = protocol.capabilities === undefined
            ? `NativeToolDescriptor::new(${JSON.stringify(protocol.binaryName)}, ${protocol.protocolVersion});`
            : `NativeToolDescriptor::with_capabilities(${JSON.stringify(protocol.binaryName)}, ${protocol.protocolVersion}, ${name}_CAPABILITIES);`;
        const declaration = `pub const ${name}: NativeToolDescriptor = ${constructor}`;
        const capabilities = protocol.capabilities === undefined
            ? ''
            : `pub const ${name}_CAPABILITIES: &[NativeToolCapability] = &[\n${protocol.capabilities.map(capability => `    NativeToolCapability::new(${JSON.stringify(capability.name)}, ${String(capability.required)}, ${capability.introducedIn}),`).join('\n')}\n];\n\n`;
        return declaration.length <= 100
            ? `${capabilities}${declaration}`
            : `${capabilities}pub const ${name}: NativeToolDescriptor =\n    ${constructor}`;
    }).join('\n\n');
    const allDescriptors = protocols.map(rustConstantName).join(', ');

    const imports = protocols.some(protocol => protocol.capabilities !== undefined)
        ? 'use crate::{NativeToolCapability, NativeToolDescriptor};'
        : 'use crate::NativeToolDescriptor;';
    return `// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.\n\n${imports}\n\n${constants}\n\npub const ALL_NATIVE_TOOL_DESCRIPTORS: &[NativeToolDescriptor] =\n    &[${allDescriptors}];\n`;
}

export async function generateNativeToolProtocols(
    options: IGenerateNativeToolProtocolsOptions = {},
) {
    const root = options.projectRoot ?? projectRoot;
    const protocols = options.protocols ?? GENERATED_RUST_NATIVE_TOOL_PROTOCOLS;
    return writeGeneratedFileIfChanged(
        path.join(root, generatedRustRelativePath),
        renderRustNativeToolProtocols(protocols),
    );
}

const isDirectCliRun = process.argv[1] !== undefined
    && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectCliRun) {
    try {
        if (process.argv.length > 2) {
            throw new Error('Usage: node --import tsx scripts/generateNativeToolProtocols.ts');
        }
        const changed = await generateNativeToolProtocols();
        if (changed) {
            console.info('Generated native tool protocol artifacts.');
        }
    } catch (error) {
        console.error(getErrorMessage(error));
        process.exitCode = 1;
    }
}
