// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.

use crate::{NativeToolCapability, NativeToolDescriptor};

pub const PDF_IMAGE_COMBINE: NativeToolDescriptor =
    NativeToolDescriptor::new("evb-pdf-image-combine", 4);

pub const PDF_PAGE_OPS: NativeToolDescriptor = NativeToolDescriptor::new("evb-pdf-page-ops", 1);

pub const PDF_SEARCH: NativeToolDescriptor = NativeToolDescriptor::new("evb-pdf-search", 1);

pub const SCAN_CLEANUP_CAPABILITIES: &[NativeToolCapability] = &[
    NativeToolCapability::new("manifest-v3", true, 1),
    NativeToolCapability::new("structured-warning-events", false, 10),
];

pub const SCAN_CLEANUP: NativeToolDescriptor =
    NativeToolDescriptor::with_capabilities("evb-scan-cleanup", 10, SCAN_CLEANUP_CAPABILITIES);

pub const ALL_NATIVE_TOOL_DESCRIPTORS: &[NativeToolDescriptor] =
    &[PDF_IMAGE_COMBINE, PDF_PAGE_OPS, PDF_SEARCH, SCAN_CLEANUP];
